# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:8

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y device-tree-compiler
          - git clone git@bitbucket.org:eruffaldi/cppposit_private.git
          - cd cppposit_private
          - git checkout feat_rvv
          - export CPPPOSIT_DIR=$(pwd)
          - cd .. && mkdir build_spike && cd build_spike
          - ../configure
          - make -j$(nproc)
          - cd .. && tar -cvzf spike_latest.tar.gz ./build_spike/spike
          - curl -X POST "https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"spike_latest.tar.gz" 
